# vim:tabstop=4:softtabstop=4:shiftwidth=4
[project]
name = "playground-uv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "debugpy>=1.8.6",
    "deepdiff>=8.0.1",
    "pytest-clarity>=1.0.1",
    "pytest>=8.3.3",
]
